- name: Install OpenJDK On Debian
  apt: pkg="openjdk-7-jre" update_cache=yes
  when: ansible_os_family == "Debian"

- name: Enable Epel CentOS
  yum: name=http://ftp.icm.edu.pl/pub/Linux/fedora/linux/epel/6/i386/epel-release-6-8.noarch.rpm state=present
  when: ansible_os_family == "RedHat"

- name: Install OpenJDK On CentOS
  yum: name=java-1.7.0-openjdk state=present
  when: ansible_os_family == "RedHat"
